site_name: Energy Assistant
nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration:
    - Configuration: config_file.md
    - Devices: device_models.md
  - About: about.md

theme: readthedocs
